USE [master]
GO
/****** Object:  Database [BankDb1]    Script Date: 04-04-2023 09:39:09 ******/
CREATE DATABASE [BankDb1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BankDb1', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BankDb1.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BankDb1_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BankDb1_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [BankDb1] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BankDb1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BankDb1] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BankDb1] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BankDb1] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BankDb1] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BankDb1] SET ARITHABORT OFF 
GO
ALTER DATABASE [BankDb1] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [BankDb1] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BankDb1] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BankDb1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BankDb1] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BankDb1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BankDb1] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BankDb1] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BankDb1] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BankDb1] SET  ENABLE_BROKER 
GO
ALTER DATABASE [BankDb1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BankDb1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BankDb1] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BankDb1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BankDb1] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BankDb1] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [BankDb1] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BankDb1] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BankDb1] SET  MULTI_USER 
GO
ALTER DATABASE [BankDb1] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BankDb1] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BankDb1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BankDb1] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BankDb1] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BankDb1] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [BankDb1] SET QUERY_STORE = OFF
GO
USE [BankDb1]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 04-04-2023 09:39:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Banks]    Script Date: 04-04-2023 09:39:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Banks](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[BranchId] [int] NOT NULL,
	[CreatedById] [int] NOT NULL,
	[CreatedDate] [datetime2](7) NOT NULL,
	[UpdatedById] [int] NULL,
	[UpdatedDate] [datetime2](7) NULL,
 CONSTRAINT [PK_Banks] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Branches]    Script Date: 04-04-2023 09:39:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Branches](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[BranchCode] [nvarchar](15) NOT NULL,
	[CreatedById] [int] NOT NULL,
	[CreatedDate] [datetime2](7) NOT NULL,
	[UpdatedById] [int] NULL,
	[UpdatedDate] [datetime2](7) NULL,
 CONSTRAINT [PK_Branches] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CustomerBanks]    Script Date: 04-04-2023 09:39:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CustomerBanks](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[BankId] [int] NOT NULL,
	[CustomerId] [int] NOT NULL,
	[AccountNumber] [nvarchar](50) NOT NULL,
	[AccountType] [int] NOT NULL,
	[Balance] [decimal](18, 2) NOT NULL,
	[IsDeleted] [bit] NOT NULL,
	[CreatedById] [int] NOT NULL,
	[CreatedDate] [datetime2](7) NOT NULL,
	[UpdatedById] [int] NULL,
	[UpdatedDate] [datetime2](7) NULL,
 CONSTRAINT [PK_CustomerBanks] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Customers]    Script Date: 04-04-2023 09:39:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customers](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](200) NOT NULL,
	[LastName] [nvarchar](200) NOT NULL,
	[PhoneNo] [nvarchar](20) NOT NULL,
	[Email] [nvarchar](200) NOT NULL,
	[IsDeleted] [bit] NOT NULL,
	[CreatedById] [int] NOT NULL,
	[CreatedDate] [datetime2](7) NOT NULL,
	[UpdatedById] [int] NULL,
	[UpdatedDate] [datetime2](7) NULL,
 CONSTRAINT [PK_Customers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Transactions]    Script Date: 04-04-2023 09:39:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Transactions](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TransactionId] [uniqueidentifier] NOT NULL,
	[BankId] [int] NOT NULL,
	[CustomerId] [int] NOT NULL,
	[Amount] [decimal](18, 2) NOT NULL,
	[TransectionDate] [datetime2](7) NOT NULL,
	[TransactionType] [int] NOT NULL,
	[TransectionRemarks] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Transactions] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Index [IX_Banks_BranchId]    Script Date: 04-04-2023 09:39:09 ******/
CREATE NONCLUSTERED INDEX [IX_Banks_BranchId] ON [dbo].[Banks]
(
	[BranchId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Transactions_BankId]    Script Date: 04-04-2023 09:39:09 ******/
CREATE NONCLUSTERED INDEX [IX_Transactions_BankId] ON [dbo].[Transactions]
(
	[BankId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Transactions_CustomerId]    Script Date: 04-04-2023 09:39:09 ******/
CREATE NONCLUSTERED INDEX [IX_Transactions_CustomerId] ON [dbo].[Transactions]
(
	[CustomerId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Banks]  WITH CHECK ADD  CONSTRAINT [FK_Banks_Branches_BranchId] FOREIGN KEY([BranchId])
REFERENCES [dbo].[Branches] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Banks] CHECK CONSTRAINT [FK_Banks_Branches_BranchId]
GO
ALTER TABLE [dbo].[Transactions]  WITH CHECK ADD  CONSTRAINT [FK_Transactions_Banks_BankId] FOREIGN KEY([BankId])
REFERENCES [dbo].[Banks] ([Id])
GO
ALTER TABLE [dbo].[Transactions] CHECK CONSTRAINT [FK_Transactions_Banks_BankId]
GO
ALTER TABLE [dbo].[Transactions]  WITH CHECK ADD  CONSTRAINT [FK_Transactions_Customers_CustomerId] FOREIGN KEY([CustomerId])
REFERENCES [dbo].[Customers] ([Id])
GO
ALTER TABLE [dbo].[Transactions] CHECK CONSTRAINT [FK_Transactions_Customers_CustomerId]
GO
USE [master]
GO
ALTER DATABASE [BankDb1] SET  READ_WRITE 
GO
